# Intro al Python

## Sostanziali Differenze con il C

Le differenze principali tra C e Pythyon, dal punto di vista della sintassi, sono le seguenti:

1. Non è necessario finire ogni riga di codice con un ";", le righe finiscono senza alcun segno di punteggiatura;

2. Python è **fortemente** sensibile all'identazione, identando una certa parte di codice si cambia  
sostanzialmente il suo funzionamento;

3. Non esiste un "main" vero e proprio, i codici iniziano direttamente dalla prima riga del "foglio" e non è  
necessario racchiudere la parte principale dello script dentro una funzione "main".

## Librerie

A differenza del C, in Python non è necessario importare librerie di base che contengano al loro interno le funzioni basilari.  
Non esiste quindi un equivalente della ben nota "stdio.h".

Possiamo quindi iniziare senza bisogno di importare nessuna libreria (per ora).

## Output

Come ogni programmatore che si rispetti, il primo argomento da affrontare consiste nello stampare una certa  
stringa di testo, nel caso del Python la funzione è "print()":

In [1]:
print('Hello World!')

Hello World!


## Varabili

Per prima cosa ci occuperemo delle variabili, in Python le variabili non necessitano di essere dichiarate insieme al loro tipo.  
Il compilatore deciderà da solo se quella che stiamo dichiarando sia di tipo int, float, double, string, etc.  

Esistono tre principali tipi di variabili:

1. Numeri;

2. Stringhe;

3. Booleani (vero o falso).

Dichiarare numeri o booleani non necessita di nessuna accortezza, Le stringhe, tuttavia, devono essere dichiarate usando  
le virgolette (o gli apostrofi).


In [3]:
# dichiariamo una variabile

numero = 1
print('Esempio di variabile: ', numero)

# dichiariamo una stringa

stringa = 'ciao'
print('Esempio di stringa: ', stringa)

# dichiariamo un booleano

booleano = True
print('Esempio di booleano: ', booleano)

Esempio di variabile:  1
Esempio di stringa:  ciao
Esempio di booleano:  True


## Input dall'utente

È possibile inserire valori da terminale usando la funzione "input()", questa funzione, tuttavia, restituisce  
di default una stringa, nel caso si sia interessati ad inserire un numero è necessario operare un  
"casting", ovvero assegnare manualmente il tipo di dato.

In [8]:
# Inseriamo da terminale una stringa

parola = input()
print('La parola inserita è: ', parola)

# Inseriamo da terminale un numero

valore = int(input())                       # esempio di casting stringa -> numero
print('Il numero inserito è: ', valore)


La parola inserita è:  ciao
Il numero inserito è:  2


## Operatori

### Operatori Aritmetici

Gli operatori aritmetici sono quelli a cui siamo abituati:

- Somma: "+"

- Differenza: "-"

- Prodotto: "*"

- Rapporto: "/"

- Modulo: "%"

- Potenza: "**"

In [17]:
a, b = 2, 3

somma = a+b
differenza = a-b
prodotto = a*b
rapporto = a/b
potenza = a**b
modulo = a%b

print("Somma di", a, "e", b, "=", somma)
print("Differenza di %d e %d = %d" % (a, b, differenza))
print("Prodotto di %d e %d = %d" % (a, b, prodotto))
print("Rapporto di %d e %d = %.2f" % (a, b, rapporto))
print("Potenza di %d e %d = %d" % (a, b, potenza))
print("Modulo di %d e %d = %d" % (a, b, modulo))

Somma di 2 e 3 = 5
Differenza di 2 e 3 = -1
Prodotto di 2 e 3 = 6
Rapporto di 2 e 3 = 0.67
Potenza di 2 e 3 = 8
Modulo di 2 e 3 = 2


### Operatori Logici e di Confronto

Vediamo gli operatori logici:

- "and": Ritorna True se entrambi gli operandi sono veri, altrimenti False;

- "or": Ritorna True se almeno uno degli operandi è vero, altrimenti False;

- "not": Ritorna False se l'operando è vero, True se l'operando è falso.

E gli operatori di confronto:

- "==:" verifica l'uguaglianza tra due operandi;

- "!=": verifica la NON uguaglianza tra due operandi;

- "<": verifica se un operando è minore dell'altro;

- "<=": verifica se un operando è minore o uguale dell'altro;

- ">": verifica se un operando è maggiore dell'altro;

- ">=": verifica se un operando è maggiore o uguale dell'altro.

In [24]:
a, b = 2, 3

# vediamo il risultato di alcune operazioni di confronto

print(a>b)
print(a==b)
print(a!=b)

# vediamo invece gli operatori logici

print(not a>b)
print(a>b and a!=b)
print(a>b or a!=b)

False
False
True
True
False
True


## Liste

Le liste rappresentano un tipo di oggetti in grado di contenere al loro interno altri oggetti, come variabili.  
Possiamo pensare ad esse come un barattolo, possiamo metterci un numero indefinito di oggetti all'interno, i quali,  
salvo terremoti improvvisi, manterranno l'ordine con cui sono stati inseriti.

Di seguito vedremo alcune operazioni sulle liste:

- Possiamo aggiungere un elemento alla fine di una lista con l'attributo ".append()", oppure al suo interno  
con l'attributo ".insert()";

- Possiamo eliminare l'ultimo elemento con l'attributo ".pop()", oppure uno specifico con ".remove()";

- Possiamo ottenere la lunghezza della lista con la funzione "len()" ed accedere ai suoi elementi  
nel modo "lista\[posizione]"

- E molte altre operazioni utili.

In [42]:
# creiamo una lista vuota

lista = []

# aggiungiamo un elemento

lista.append(3)
print(lista)

[3]


In [43]:
# possiamo aggiungere elementi di diverso tipo

lista.append('ciao')

# oppure anche sequenze di elementi

lista.extend((True, -5))

print(lista)

[3, 'ciao', True, -5]


In [44]:
# facciamo una copia della lista e rimuoviamo qualche elemento

lista_copy = lista.copy()

lista_copy.pop()

print(lista_copy)

[3, 'ciao', True]


In [45]:
# oppure il secondo elemento

lista_copy.remove('ciao')
print(lista_copy)

# stampiamo anche la lunghezza della lista e della sua copia
print('Lunghezza lista originale = ', len(lista))
print('Lunghezza lista modificata = ', len(lista_copy))

[3, True]
Lunghezza lista originale =  4
Lunghezza lista modificata =  2


In [49]:
# possiamo anche unire due liste diverse

lista1 = [2, 1, 3]
lista2 = [6, 4, 5]

lista_tot = lista1 + lista2
print("Liste unite: ", lista_tot)

# e disporre la lista ottenuta in ordine

lista_tot.sort()
print("Lista ordinata: ", lista_tot)

Liste unite:  [2, 1, 3, 6, 4, 5]
Lista ordinata:  [1, 2, 3, 4, 5, 6]


## If, Else If & Else

- "if" è una parola chiave utilizzata per eseguire un blocco di istruzioni solo se una condizione è vera.  
Ad esempio, if x > 5: eseguirà il blocco di codice che segue solo se la variabile x è maggiore di 5;

- "if else" visto in C viene rimpiazzato da "elif" ma ha lo stesso significato, viene utilizzato per  
verificare una condizione successiva al primo "if";

- "else" viene utilizzato quando tutte le altre opzioni sono state guidicate false per eseguire una parte  
di codice senza una richiesta specifica.

In [55]:
# vediamo una semplice applicazione per verificare se un numero sia positivo, negativo o zero

num = 0

if num < 0:
    print('Il numero è negativo')

elif num > 0:
    print('Il numero è positivo')

else:
    print('Il numero è zero')

Il numero è zero


## While Loop

I while loop vengono utilizzati per eseguire un blocco di codice continuamente se una certa condizione resta  
sempre verficata.

Vediamo un esempio:

In [65]:
# inizializziamo la variabile di controllo

n = 0

while n < 5:

    print('Valore di n = ', n, "--> siamo dentro il loop")

    n += 1      # questa dicitura è l'abbreviazione di n = n + 1


print("Valore di n =", n, "--> siamo usciti dal loop")

Valore di n =  0 --> siamo dentro il loop
Valore di n =  1 --> siamo dentro il loop
Valore di n =  2 --> siamo dentro il loop
Valore di n =  3 --> siamo dentro il loop
Valore di n =  4 --> siamo dentro il loop
Valore di n = 5 --> siamo usciti dal loop


## For Loop

Notiamo che nel loop while abbiamo usato una variabile di controllo incrementandola manualmente ad ogni giro,  
un modo più comodo e rapido di fare la stessa cosa consiste nell'usare i for loop.  

I for loop eseguono un blocco di codice oer un numero di step che decidiamo agendo sulla variabile  
di controllo.

Vediamo un esempio

In [66]:
# Facciamo la stessa cosa di prima ma con i loop for

for i in range(5):

    print('Valore di n = ', i, "--> siamo dentro il loop")

print("Valore di n =", i, "--> siamo usciti dal loop")

Valore di n =  0 --> siamo dentro il loop
Valore di n =  1 --> siamo dentro il loop
Valore di n =  2 --> siamo dentro il loop
Valore di n =  3 --> siamo dentro il loop
Valore di n =  4 --> siamo dentro il loop
Valore di n = 4 --> siamo usciti dal loop


Notiamo subito due cose:

1. La variabile i incrementa da sola, senza bisogno di una nostra azione;

2. Siamo usciti dal loop allo stesso momento ma la variabile vale 4 e non 5, questo in quanto  
nel loop while l'ultima azione da noi eseguita è stata incrementare la n da 4 a 5, per poi uscire  
dal loop.

## Array

Il linguaggio Python non consente di utilizzare gli array in maniera nativa come nel caso  
di altri linguaggi di programmazione.  
Tuttavia la loro implementazione è presente nella libreria *numpy*; questa libreria è così largamente utilizzata da essere, a volte, considerata un'estensione diretta di Python.  

Essendo una libreria è necessario che venga importata nel nostro codice, è buona pratica, quando si aggiungono librerie, che vengano importate con un *alias* in modo da evitare conflitti con funzioni che hanno lo stesso nome. Questa situazione è più frequente di quanto si creda, soprattutto per progetti di grande dimensione.

In [18]:
# importiamo numpy con un alias
import numpy as np

# creiamo un array unidimensionale, la chiamata della funzione array deve essere
# anticipata dall'alias della libreria seguito da un punto come di seguito
arr1d = np.array([1, 2, 3])
print("Array unidimensionale:\n{}\n".format(arr1d))


# possiamo creare anche array bidimensionali
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array bidimanionale:\n{}\n".format(arr2d))

# o anche un array in 3d
arr3d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array tridimensionale:\n", arr3d)

Array unidimensionale:
[1 2 3]

Array bidimanionale:
[[1 2 3]
 [4 5 6]]

Array tridimensionale:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


È il momento opportuno per introdurre il concetto di *slicing*. Lo slicing, letteralmente "tagliare", consiste nel selezionare solamente una parte di un array, da un certo valore ad un altro.

In [26]:
# dichiariamo un array molto un lungo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Array intero:\n{}\n".format(arr))

# effettuiamo un slicing sull'array in modo da mantenere
# solo i valori dopo il terzo (non incluso)
sliced_arr = arr[3:]
print("Array con slicing\n{}\n".format(sliced_arr))

# facciamone un altro per mantenere i valori centrali
sliced_arr_bis = arr[3:6]
print("Array con slicing bis \n{}\n".format(sliced_arr_bis))

Array intero:
[1 2 3 4 5 6 7 8 9]

Array con slicing
[4 5 6 7 8 9]

Array con slicing bis 
[4 5 6]



La domanda che potremmo farci ora è: qual'è la reale differenza tra array e liste dato che posso creare liste che contengano altre liste (un po' come la struttura degli array)?  

La risposta sta nel fatto che, pur sembrando rappresentazioni simili, gli array vengono trattati a tutti gli effetti come matrici, introducendo la nozione di righe e di colonne.  

Quando chiamiamo un array gli indici che inseriamo non sono casuali, ma corrispondono a  
[righe, colonne].

In [29]:
# accediamo alla prima colonna dell'array in 2d definito sopra utilizzando
# uno slicing ma senza argomenti, questa sintassi restituisce
# tutti gli elementi contenuti
colonna1 = arr2d[:,0]
colonna2 = arr2d[:,1]
riga1 = arr2d[0,:]

print("Prima colonna:\n{}\n".format(colonna1))
print("Seconda colonna:\n{}\n".format(colonna2))
print("Prima riga:\n{}\n".format(riga1))


Prima colonna:
[1 4]

Seconda colonna:
[2 5]

Prima riga:
[1 2 3]



Inoltre tutte le funzioni della libreria *numpy* sono ottimizzate per lavorare con array, proviamo ora a sommare tutti gli elementi contenuti in arr2d sia con la funzione somma presente di default in Python sia con quella contenuta in *numpy*.

In [30]:
somma_python = sum(arr2d)
somma_numpy = np.sum(arr2d)

print("Somma con sum() di Python: ", somma_python)
print("\nSomma con sum() di Numpy: ", somma_numpy)

Somma con sum() di Python:  [5 7 9]

Somma con sum() di Numpy:  21


Come è possibile vedere il risultato è ben diverso, la funzione somma contenuta in Python non è in grado di riconoscere l'array e ci restituisce la somma degli elementi disposti nelle colonne, piuttosto che quella di tutti gli elementi.  

Possiamo inoltre notare che le funzioni hanno lo stesso nome, in casi come questi importare una libreria con un *alias* consente a Python di capire quale delle due vogliamo utilizzare.

# Esercizi

Vediamo ora qualche esercizio per mettere in pratica quello che abbiamo visto nelle righe precedenti

## Primo Codice

Costruiamo un codice che verifichi se un numero sia primo o meno

In [7]:
# chiediamo all'utente di inserire il numero da verificare

num = int(input('Inserisci un numero: '))

# inizializziamo una variabile di controllo

flag = 0

# creiamo un loop che scorra su tutti i possibili divisori, i loop ammettono solamente
# valori di start e stop interi, mentre num/2 potrebbe essere float. La soluzione è eseguire
# un casting che tronchi la parte decimale della divisione

for i in range(2, int(num/2)):

    if num%i == 0:      # il simbolo % ci restituisce il resto della divisione
        flag = 1        # "accendiamo" la variabile di controllo
        break           # una volta trovato un divisore non serve continuare, usciamo dal loop con la condizione "break"

if flag == 1:
    print('Il numero non è primo')

else:
    print('Il numero è primo')

Il numero è primo


## Secondo Codice

Creiamo un codice per ottenere la sequenza di Fibonacci

In [7]:
# chiediamo all'utente quanti numeri della sequenza vuole visualizzare

num = int(input('Quanti elementi della sequenza vuoi vedere? '))

#inizializziamo ue variabili che ci serviranno per la sequenza
a, b = 1, 0

# distinguiamo il caso in cui si viglia solamente un valore della sequenza
if num == 1:
    print(a)

# scriviamo qua il loop che ci permetterà di ottenere anche gli altri elementi della successione
else:

    # primo termine
    print(a)

    # fermiamo il loop un valore prima di quello che vogliamo dato che abbiamo già stampato il primo termine
    for i in range(num - 1):

        c = a + b
        b = a
        a = c
        print(c)



1
1
2
3
5
8
13
21
34
55


## Terzo Codice

Chiediamo all'utente di inserire una serie di numeri, il programma dovrà restituirli ordinati

In [13]:
# per prima cosa chiediamo all'utente quanti numeri vuole inserire
num = int(input('Quanti numeri vuoi inserire? '))

# inizializziamo una lista per contenere i numeri
lista = []

# ora creiamo un loop per inserire i numeri nella lista
for i in range(num):
    numero = int(input('Inerisci un numero: '))

    # aggiungiamo il numero inserito alla lista
    lista.append(numero)

# Creiamo una copia della lista originale per ordinare i numeri
lista_ord = lista.copy()

# Creiamo ora due loop per ordinare la lista, scrivendoli in questo modo facciamo si
# che si confrontino SOLO elementi ADIACENTI fra loro

for i in range(num - 1):
    for j in range(num - 1 - i):

        # Confrontiamo gli elementi adiacenti e li scambiamo se necessario
        if lista_ord[j] > lista_ord[j + 1]:
            lista_ord[j], lista_ord[j + 1] = lista_ord[j + 1], lista_ord[j]

print("Lista originale:", lista)
print("Lista ordinata:", lista_ord)

Lista originale: [4, 6, 3, 4, 5, 6, 3, 4, 5, 6]
Lista ordinata: [3, 3, 4, 4, 4, 5, 5, 6, 6, 6]


Modifichiamo il codice precedente in modo che non sia necessario dire quanti numeri vogliamo inserire all'inizio

In [20]:
# inizializziamo una lista per contenere i numeri
lista = []

# ora creiamo un loop per inserire i numeri nella lista, usiamo un loop "infinito"
while True:

    # per ora trattiamo i numeri come stringhe
    numero_stringa = input('Inerisci un numero: ')

    # interrompiamo il ciclo quando l'utente schiaccia invio senza inserire nulla
    if numero_stringa == '':
        break

    # convertiamo il numero da stringa a intero
    numero = int(numero_stringa)

    # aggiungiamo il numero inserito alla lista
    lista.append(numero)

# Creiamo una copia della lista originale per ordinare i numeri
lista_ord = lista.copy()

# Creiamo ora due loop per ordinare la lista, scrivendoli in questo modo facciamo si
# che si confrontino SOLO elementi ADIACENTI fra loro. Invece di avere un loop che
# scorre sino ad un numero inserito dall'utente lo facciamo scorrere sino alla 
# lunghezza massima della lista di numeri

for i in range(len(lista) - 1):
    for j in range(len(lista) - 1 - i):

        # Confrontiamo gli elementi adiacenti e li scambiamo se necessario
        if lista_ord[j] > lista_ord[j + 1]:
            lista_ord[j], lista_ord[j + 1] = lista_ord[j + 1], lista_ord[j]

print("Lista originale:", lista)
print("Lista ordinata:", lista_ord)

Lista originale: [3, 5, 4, 3, 7, 6]
Lista ordinata: [3, 3, 4, 5, 6, 7]
